### ISSUE TITLE
Stop using .throw method on coroutines

### ISSUE THREAD

**Issue by njsmith** [njsmith/trio#38]
If an exception is raised inside an `except` block, Python does its lovely implicit exception chaining thing and shows us both tracebacks:
```python
# Regular raise of KeyError while handling ValueError
def f():
    try:
        raise ValueError
    except:
        raise KeyError

>> f()
Traceback (most recent call last):
  File "<stdin>", line 3, in f
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in f
KeyError
```

But if you use `.throw()` to inject an exception, then this does not happen – all record of the `ValueError` is lost! (Using generators in the example instead of coroutines b/c there's less boilerplate:)
```python
# .throw() raises a KeyError while handling ValueError
def f2():
    try:
        raise ValueError
    except:
        yield

>>> gen = f2(); gen.send(None); gen.throw(KeyError)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in f2
KeyError
```

This can be avoided by avoiding `throw`, and instead `send`ing in the exception object and re-raising it inside the generator callstack:
```python
def f3():
    try:
        raise ValueError
    except:
        raise (yield)

>>> gen = f3(); gen.send(None); gen.send(KeyError)  # notice "send", not "throw"!
Traceback (most recent call last):
  File "<stdin>", line 3, in f3
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in f3
KeyError
```

Making this change for us is really easy -- right now to resume a coroutine we take a `Result` object, and have it either `send` or `throw` the unwrapped version of itself into the `yield_*` trap. All we need to do is switch it so we `send` in the `Result` object, and then have the `yield_*` trap call `unwrap`.

**Comment by njsmith** [comment]
done
